# Use an official Python runtime as a base image
FROM python:3.8

# Set the working directory in the container to /app
WORKDIR /app

# Copy the requirements.txt file into the container at /app
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application's code into the container at /app
COPY . .

# Make port 5000 available outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=redshift_flask.py

# Run the Flask application
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
